version: "3.8"

services:
  app:
    container_name: able-alliance-app
    build:
      dockerfile: ./Dockerfile.dev
    environment:
      MONGODB_URI: "mongodb://mongo:27017/able-alliance?replicaSet=rs0"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - ./app-init.sh:/app/app-init.sh
    ports:
      - "3000:3000"
    networks:
      - able-alliance-net
    depends_on:
      mongo:
        condition: service_healthy
    entrypoint: ["/bin/bash", "./app-init.sh"]

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    networks:
      - able-alliance-net
    entrypoint: ["/bin/bash", "/app/mongo-init.sh"]
    volumes:
      - mongodb-data:/data/db
      - ./mongo-init.sh:/app/mongo-init.sh
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "rs.status().ok", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

networks:
  able-alliance-net:
    driver: bridge

volumes:
  mongodb-data:
  node_modules:
